# Generated by Django 4.1.7 on 2023-03-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0003_comment_parent_comment_childcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.DeleteModel(
            name='ChildComment',
        ),
    ]
